version: "3.9"

services:
  app:
    image: ghcr.io/tomhaeck/portfolio:${IMAGE_TAG:-latest}
    container_name: portfolio_app
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - ./db:/app/db
      - ./media:/app/media
      - ./static:/app/staticfiles

  nginx:
    image: nginx:stable
    container_name: portfolio_nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./static:/static:ro
      - ./media:/media:ro
