name: Build and Deploy

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/tomhaeck/portfolio
  IMAGE_TAG: ${{ github.sha }}
  CONTAINER_NAME: portfolio

jobs:
  build-and-push-to-github-registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
          -t "${IMAGE_NAME}:${IMAGE_TAG}" \
          -t "${IMAGE_NAME}:latest" \
          .

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push "${IMAGE_NAME}:${IMAGE_TAG}"
          docker push "${IMAGE_NAME}:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-to-github-registry

    steps:
      - name: Configure SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          set -euxo pipefail

          IMAGE_NAME="${IMAGE_NAME}"
          CONTAINER_NAME="${CONTAINER_NAME}"
          
          docker stop "$CONTAINER_NAME" 2>/dev/null || true
          docker rm "$CONTAINER_NAME" 2>/dev/null || true

          docker run -d \
            --name "$CONTAINER_NAME" \
            -p 80:8000 \
            "${IMAGE_NAME}:${IMAGE_TAG}"
          
          docker exec "$CONTAINER_NAME" python manage.py migrate --noinput
          
          EOF
